INSERT INTO TASK_MODELV1(`TASK_ID`, `TASK_NAME`) VALUES (NEXT VALUE FOR task_id_seq, 'task1'),
                                                        (NEXT VALUE FOR task_id_seq, 'task2'),
                                                        (NEXT VALUE FOR task_id_seq, 'task3'),
                                                        (NEXT VALUE FOR task_id_seq, 'task4'),
                                                        (NEXT VALUE FOR task_id_seq, 'task5'),
                                                        (NEXT VALUE FOR task_id_seq, 'task6'),
                                                        (NEXT VALUE FOR task_id_seq, 'task7'),
                                                        (NEXT VALUE FOR task_id_seq, 'task8'),
                                                        (NEXT VALUE FOR task_id_seq, 'task9'),
                                                        (NEXT VALUE FOR task_id_seq, 'task10'),
                                                        (NEXT VALUE FOR task_id_seq, 'task11'),
                                                        (NEXT VALUE FOR task_id_seq, 'task12'),
                                                        (NEXT VALUE FOR task_id_seq, 'task13'),
                                                        (NEXT VALUE FOR task_id_seq, 'task14');